my_dict = {'ukraine': 6, 'hitting': 1, 'russi': 11, 'hard': 1,
           'regions': 7, 'moscow': 2, 'trying': 1, 'seize': 1,
           'joshu': 1, 'berlinger': 1, 'olg': 1, 'voitovych': 1,
           'cnn': 2, 'updated:': 1, 'tue': 1, '04': 1, 'oct': 1,
           '2022': 1, '16:47:10': 1, 'gmt': 1, 'source:': 1,
           'vladimir': 1, 'put': 7, 'lost': 2, 'more': 3,
           'ukrainian': 7, 'territory': 3, 'he': 1, 'seeking': 1,
           'annex': 3, 'h': 9, 'government': 2, 'on': 11, 'tuesday': 9,
           'sought': 2, 'finalize': 1, 'formalities': 1, 'claim': 2,
           'four': 3, 'none': 1, 'which': 4, 'are': 7, 'fully': 1,
           'controlled': 1, 'anymore': 1, 'upper': 1, 'house': 1,
           "russia's": 2, 'rubber-stamp': 1, 'legislature': 1,
           'federation': 1, 'council': 1, 'unanimously': 1,
           'approved': 1, 'decision': 1, 'donetsk': 3, 'kherson': 5,
           'luhansk': 3, 'zaporizhzhi': 2, 'defiance': 1, 'international': 1,
           'law': 1, 'day': 3, 'after': 3, 'lower': 1, 'chamber': 1, 'had': 1,
           'done': 1, 'same': 1, 'president': 1, 'expected': 1, 'sign': 1,
           'legislation': 1, 'later': 2, 'spokesman': 2, 'said': 5, "kyiv's": 2,
           'military': 4, 'however': 1, 'continued': 2, 'advance': 1, 'several': 1,
           'now': 2, 'claims': 1, 'own': 2, 'spurring': 1, 'questions': 1, 'about': 1,
           'whether': 1, 'kreml': 4, 'can': 1, 'hold': 1, 'parts': 1, 'those': 3,
           'territories': 1, 'it': 5, 'currently': 1, 'controls': 1, '--': 5, 'even': 1,
           'what': 1, 'would': 6, 'consider': 1, 'new': 2, 'border': 1, 'annexation': 3,
           'dmitry': 1, 'peskov': 2, 'monday': 3, 'needed': 1, '"continue': 1, 'consulting"': 1,
           'local': 1, 'populations': 1, 'before': 1, 'establishing': 1, 'boundaries': 1,
           'how': 2, 'plans': 1, 'take': 1, 'remains': 1, 'unclear': 1, 'at': 5, 'le': 1,
           't': 4, 'short-term': 1, 'hinted': 1, 'l': 2, 'week': 1, 'will': 2, 'attempt': 1,
           'retake': 2, 'date': 1, 'campaign': 1, 'likely': 1, 'involve': 1, 'some': 1, '300': 1,
           '000': 2, 'reservists': 1, 'being': 1, 'called': 1, 'up': 2, 'part': 1, '"partial': 1,
           'mobilization"': 1, 'ordered': 1, 'month': 2, 'russian': 6, 'defense': 3, 'minister': 1,
           'sergei': 1, 'shoigu': 1, 'than': 1, '200': 1, 'people': 4, 'have': 7, 'joined': 1,
           "country's": 2, 'since': 3, 'announcement': 1, 'sparked': 1, 'protests': 1, 'sent': 1,
           'hundreds': 1, 'thousands': 1, 'mostly': 1, 'fighting-age': 1, 'men': 1, 'fleeing': 1,
           'neighboring': 1, 'countries': 1, 'forces': 4, 'continuing': 1, 'push': 3, 'ahead': 1,
           'their': 2, 'surprisingly': 1, 'successful': 1, 'counteroffensive': 1, 'seen': 1, 'one': 4,
           'official': 1, 'liberated': 1, '"every': 1, '"': 6, 'sunday': 1, 'kyiv': 2, 'took': 2,
           'control': 1, 'lyman': 3, 'an': 1, 'important': 1, 'logistical': 1, 'railway': 1,
           'hub': 1, 'army': 1, 'used': 1, 'funnel': 1, 'troops': 3, 'supplies': 1, 'west': 1,
           'south': 2, 'ministry': 2, 'forced': 1, 'cede': 1, 'or': 4, 'risk': 1, 'encirclement': 1,
           'there': 4, 'allowing': 1, 'potentially': 1, 'use': 2, 'city': 1, 'staging': 1, 'post': 1,
           'further': 2, 'e': 2, 'victory': 1, 'followed': 2, 'gains': 2, 'success': 3, 'toward': 1,
           'overnight': 1, 'saw': 1, 'towns': 1, 'davydiv': 1, 'brid': 1, 'velyk': 1, 'oleksandrivk': 1,
           '"ukrainian': 1, 'marines': 1, 'confidently': 1, 'advancing': 1, 'towards': 1, 'black': 1,
           'se': 1, "ukraine's": 2, 'tweeted': 1, 'announced': 2, 'both': 2, 'tern': 1, 'fighting': 1,
           'against': 2, 'moscow-backed': 1, 'breakaway': 1, 'republics': 1, 'each': 1, 'region': 2,
           'been': 4, 'raging': 1, '2014': 1, 'southern': 1, 'occupied': 1, 'shortly': 1, 'inv': 1,
           'ion': 1, 'began': 1, 'late': 1, 'february': 1, 'recent': 3, 'not': 2, 'pro-russian': 1,
           'bloggers': 1, 'propagandists': 1, 'unusually': 1, 'critical': 1, 'war': 3, 'effort': 1,
           'days': 2, 'though': 1, 'were': 4, 'no': 1, 'votes': 1, 'parliament': 1, 'senator': 1,
           'aired': 1, 'concerns': 2, 'be': 4, 'absorbing': 1, '"occupied': 1, 'armed': 1, 'another': 1,
           'country': 1, 'defeats': 1, 'piling': 1, 'changes': 1, 'appear': 1, 'store': 1, 'machine': 1,
           'records': 1, 'show': 1, 'recently': 1, 'removed': 1, 'col': 1, 'gen': 1, 'alexander': 1,
           'zhuravlyov': 1, 'head': 1, 'western': 2, 'district': 1, 'five': 1, 'such': 1, 'districts': 1,
           'key': 1, 'player': 1, 'us': 3, 'officials': 2, 'voiced': 2, 'may': 1, 'escalate': 1, 'conflict': 1,
           'response': 1, 'battlefield': 1, 'w': 1, 'hington': 1, 'considering': 1, 'respond': 1, 'range': 1,
           'potential': 1, 'scenarios': 1, 'including': 2, 'if': 1, 'tactical': 1, 'nuclear': 2, 'weapons': 1,
           'according': 1, 'three': 1, 'sources': 1, 'briefed': 1, 'latest': 1, 'intelligence': 1, 'caution': 1,
           'detected': 1, 'preparations': 1, 'strike': 1, 'many': 1, "world's": 1, 'developed': 1, 'democracies': 1,
           'continually': 1, 'strong': 1, 'opposition': 1, 'entire': 1, 'process': 1, 'so-called': 1, 'referendums': 1,
           'held': 1, 'attempting': 1, 'staged': 1, 'contests': 1, 'purportedly': 1, 'showed': 1, 'majority': 1,
           'living': 2, 'wanted': 1, 'jo': 1, 'widely': 1, 'panned': 1, 'farce': 1, 'failed': 1, 'meet': 1,
           'internationally': 1, 'recognized': 1, 'standards': 1, 'free': 1, 'fair': 1, 'elections': 1, 'reports': 1,
           'from': 2, 'ground': 1, 'suggested': 1, 'voting': 1, 'place': 1, 'essentially': 1, 'literally': 1,
           'gunpoint': 1, 'results': 1, 'fiery': 1, 'speech': 1, "kremlin's": 2, 'st': 1, "george's": 1, 'friday': 1,
           'address': 1, 'annexed': 1, 'millions': 1, 'citizens': 1, '"forever': 1, 'deputy': 1, 'foreign': 1,
           'residents': 1, 'change': 1, 'citizenship': 1, 'members': 1, 'g7': 1, 'canad': 1, 'france': 1,
           'germany': 1, 'italy': 1, 'japan': 1, 'united': 2, 'kingdom': 1, 'states': 1, 'european': 1,
           'union': 1, 'responded': 1, 'saying': 1, 'they': 1, 'never': 1, 'recognize': 1, 'sovereignty': 2,
           'over': 1, 'vowing': 1, '"impose': 1, 'economic': 1, 'costs': 1, 'leaders': 1, 'unveil': 1,
           'sanctions': 1, "putin's": 1, 'regime': 1, 'uk': 1, 'sanctioned': 1, 'leader': 1, '"destabilizing': 1,
           'undermining': 1, 'threatening': 1, 'territorial': 1, 'integrity': 1, 'independence': 1}

print(list(my_dict.values()))